name = "vault-mcp"
main = "src/index.ts"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "VAULT_DB"
database_name = "vault-db"
database_id = "5a0c53ff-963c-48f9-b68d-f13536104aa1"

[[kv_namespaces]]
binding = "TASKS_KV"
id = "0e01cc2910764d66a3cf8910f8e25eff"

[[migrations]]
tag = "v1"
new_classes = ["McpAgent"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "McpAgent", to = "VaultMcpAgent" }]

[[migrations]]
tag = "v3"
deleted_classes = ["VaultMcpAgent"]


[ai]
binding = "AI"
